---
- name: fedora | install essentials
  become: yes
  ansible.builtin.dnf:
    name:
      - vim
      - python3-pip
      - jq
      - git
    state: present

- name: add hasicorp repo
  become: yes
  command: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

- name: install terraform
  become: yes
  ansible.builtin.dnf:
    name: terraform
    state: present
