---
- hosts: localhost
  connection: local

  tasks:
    - name: setup debian
      include_tasks: debian.yml
      when: ansible_os_family == 'Debian'

    - name: setup Fedora
      include_tasks: fedora.yml
      when: ansible_distribution == 'Fedora'

    - name: install python packages
      ansible.builtin.pip:
        requirements: requirements.txt
      args:
        chdir: .
